(function(){'use strict';var q=function(a,b,c){return a.call.apply(a.bind,arguments)},r=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var e=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,e);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},t=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?t=q:t=r;return t.apply(null,arguments)};var u=/&/g,v=/</g,w=/>/g,y=/"/g,aa=/'/g,ba=/\x00/g,ca=/[\x00&<>"']/,da=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};var A=function(){this.f=z};A.prototype.o=!0;A.prototype.l=function(){return""};A.prototype.toString=function(){return"Const{}"};var C=function(a){return a instanceof A&&a.constructor===A&&a.f===z?"":"type_error:Const"},z={};var E=function(){this.f=D};E.prototype.o=!0;var D={};E.prototype.l=function(){return""};var ea=function(a){return a instanceof E&&a.constructor===E&&a.f===D?"":"type_error:SafeScript"};var G=function(){this.f=F};G.prototype.o=!0;var F={};G.prototype.l=function(){return""};var fa=function(a){return a instanceof G&&a.constructor===G&&a.f===F?"":"type_error:SafeStyle"};var I=function(){this.f=H};I.prototype.o=!0;I.prototype.l=function(){return""};var ga=function(a){return a instanceof I&&a.constructor===I&&a.f===H?"":"type_error:TrustedResourceUrl"},H={};var K=function(){this.f="";this.A=J};K.prototype.o=!0;K.prototype.l=function(){return this.f};var ha=function(a){return a instanceof K&&a.constructor===K&&a.A===J?a.f:"type_error:SafeUrl"},ia=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,J={},L=function(a){var b=new K;b.f=a;return b};L("about:blank");var N=function(){this.f=M};N.prototype.o=!0;N.prototype.l=function(){return""};var ja=function(a){return a instanceof N&&a.constructor===N&&a.f===M?"":"type_error:SafeHtml"},M={};/*

 Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at
 http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at
 http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at
 http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at
 http://polymer.github.io/PATENTS.txt
*/
var ka={align:1,alt:1,autofocus:1,bgcolor:1,border:1,checked:1,"class":1,color:1,cols:1,colspan:1,dir:8,disabled:1,draggable:1,face:1,"for":10,frameborder:1,height:1,hidden:1,href:4,id:10,ismap:1,label:1,lang:1,loop:1,max:1,maxlength:1,min:1,multiple:1,muted:1,name:10,placeholder:1,preload:1,rel:1,required:1,reversed:1,role:1,rows:1,rowspan:1,selected:1,shape:1,size:1,sizes:1,span:1,spellcheck:1,src:4,start:1,step:1,style:5,summary:1,tabindex:1,target:8,title:1,translate:1,valign:1,value:1,width:1,
wrap:1},O={a:{href:[{c:3}]},area:{href:[{c:3}]},audio:{src:[{c:3}]},blockquote:{cite:[{c:3}]},button:{formaction:[{c:3}],formmethod:[{c:1}],type:[{c:1}]},command:{type:[{c:1}]},del:{cite:[{c:3}]},form:{action:[{c:3}],method:[{c:1}]},img:{src:[{c:3}]},input:{formaction:[{c:3}],formmethod:[{c:1}],max:[{c:1}],min:[{c:1}],src:[{c:3}],step:[{c:1}],type:[{c:1}]},ins:{cite:[{c:3}]},li:{type:[{c:1}]},link:{href:[{c:3,g:"rel",h:"alternate"},{c:3,g:"rel",h:"author"},{c:3,g:"rel",h:"bookmark"},{c:3,g:"rel",
h:"canonical"},{c:3,g:"rel",h:"cite"},{c:3,g:"rel",h:"help"},{c:3,g:"rel",h:"icon"},{c:3,g:"rel",h:"license"},{c:3,g:"rel",h:"next"},{c:3,g:"rel",h:"prefetch"},{c:3,g:"rel",h:"prerender"},{c:3,g:"rel",h:"prev"},{c:3,g:"rel",h:"search"},{c:3,g:"rel",h:"subresource"}],media:[{c:1}],type:[{c:1}]},menuitem:{icon:[{c:3}]},ol:{type:[{c:1}]},q:{cite:[{c:3}]},source:{media:[{c:1}],src:[{c:3}]},style:{media:[{c:1}]},video:{poster:[{c:3}],src:[{c:3}]}},P={a:1,abbr:1,address:1,applet:4,area:5,article:1,aside:1,
audio:1,b:1,base:4,bdi:1,bdo:1,blockquote:1,body:1,br:5,button:1,canvas:1,caption:1,cite:1,code:1,col:5,colgroup:1,command:1,data:1,datalist:1,dd:1,del:1,details:1,dfn:1,dialog:1,div:1,dl:1,dt:1,em:1,embed:4,fieldset:1,figcaption:1,figure:1,font:1,footer:1,form:1,frame:1,frameset:1,h1:1,h2:1,h3:1,h4:1,h5:1,h6:1,head:1,header:1,hr:5,html:1,i:1,iframe:4,img:5,input:5,ins:1,kbd:1,keygen:5,label:1,legend:1,li:1,link:5,main:1,map:1,mark:1,math:4,menu:1,menuitem:1,meta:4,meter:1,nav:1,noscript:1,object:4,
ol:1,optgroup:1,option:1,output:1,p:1,param:5,picture:1,pre:1,progress:1,q:1,rb:1,rp:1,rt:1,rtc:1,ruby:1,s:1,samp:1,script:3,section:1,select:1,slot:1,small:1,source:5,span:1,strong:1,style:2,sub:1,summary:1,sup:1,svg:4,table:1,tbody:1,td:1,template:4,textarea:1,tfoot:1,th:1,thead:1,time:1,title:1,tr:1,track:5,u:1,ul:1,"var":1,video:1,wbr:5},la=[{auto:!0,ltr:!0,rtl:!0},{_self:!0,_blank:!0}],Q={"*":{dir:0,target:1}};var U=function(){if(!R){var a=ma,b={};for(c in a)b[c]=a[c];R=b;a=0;for(b=S.length;a<b;++a){var c=S[a];R[c.toLowerCase()]=c}}return R},S="aLink accessKey allowFullscreen bgColor cellPadding cellSpacing codeBase codeType contentEditable crossOrigin dateTime dirName formAction formEnctype formMethod formNoValidate formTarget frameBorder innerHTML innerText inputMode isMap longDesc marginHeight marginWidth maxLength mediaGroup minLength noHref noResize noShade noValidate noWrap nodeValue outerHTML outerText readOnly tabIndex textContent trueSpeed useMap vAlign vLink valueAsDate valueAsNumber valueType".split(" "),
ma={accept_charset:"acceptCharset","char":"ch",charoff:"chOff",checked:"defaultChecked","class":"className","for":"htmlFor",http_equiv:"httpEquiv",muted:"defaultMuted",selected:"defaultSelected",value:"defaultValue"},R=null,V=null;var W={},X=!1,Y=0,na=/^(?!(?:annotation-xml|color-profile|font-face|font-face(?:-(?:src|uri|format|name))?|missing-glyph)$)[a-z][a-z.0-9_\u00b7\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u037d\u200c\u200d\u203f-\u2040\u2070-\u218f\u2c00-\u2fef\u3001-\udfff\uf900-\ufdcf\ufdf0-\ufffd]*-[\-a-z.0-9_\u00b7\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u037d\u200c\u200d\u203f-\u2040\u2070-\u218f\u2c00-\u2fef\u3001-\udfff\uf900-\ufdcf\ufdf0-\ufffd]*$/,Z=function(a,b){var c=window.customElements;if(X){for(var e=Polymer.telemetry.registrations,
g=e.length,x=Y;x<g;++x)W[e[x].is]=W;Y=g}return c&&c.get(a)||W[a]===W?2:b===HTMLUnknownElement?1:b===HTMLElement&&na.test(a)?3:0};var oa=/^$/;
(function(){function a(){function c(c){var a=this.getAttribute(c);return!a||/[\[\{]/.test(c)?null:a}function a(a,k,f,d){if(!d)return d;var e=a.nodeType;if(1!==e){if(3===e&&(e=a.parentElement)&&1===e.nodeType){a=e.localName;k=!1;switch(Z(a,e.constructor)){case 0:case 1:k=1===(Object.hasOwnProperty.call(P,a)?P[a]:null);break;case 3:case 2:k=!0}if(k)return d&&d.o?d.l():String(d)}return"zClosurez"}var e=a.localName;var l=a.localName;if(a.getAttribute("is")||2!==Z(l,a.constructor)){var h=g[l];h||(h=g[l]=
document.createElement(l));l=h}else l=x;switch(f){case "attribute":var h=String(k).toLowerCase(),B=U()[h];if(("string"==typeof B?B:da(h))in l)break;return d;case "property":if(k in l)break;h=k.toLowerCase();h=U()[h];if((h="string"==typeof h?h:null)&&h in l)break;return d;default:throw Error(f+": "+typeof f);}if("attribute"==f)k=k.toLowerCase();else{f=V;if(!f){f=U();l={};for(var m in f)l[f[m]]=m;f=V=l}m=f[k];k="string"==typeof m?m:String(k).replace(/([A-Z])/g,"-$1").toLowerCase()}a:{a=t(c,a);if(Object.hasOwnProperty.call(O,
e)&&(m=O[e],Object.hasOwnProperty.call(m,k)&&(m=m[k],m instanceof Array))){f=null;l=!1;h=0;for(B=m.length;h<B;++h){var n=m[h],p=n.g;if(!p){a=n.c;break a}null===f&&(f={});p=Object.hasOwnProperty.call(f,p)?f[p]:f[p]=a(p);if(p===n.h){a=n.c;break a}null==p&&(l=!0)}if(l){a=null;break a}}a=ka[k];a="number"===typeof a?a:null}m="zClosurez";if(null!=a){a=b[a];if(a.j&&d instanceof a.j)return a.m(d);d=d&&d.o?d.l():String(d);m=a.filter?a.filter(e,k,d):d}return m}console.log("initResin");var g={},x=document.createElement("polyresinuncustomized");
if(/^1\./.test(Polymer.version)){X=!0;var pa=Polymer.Base.w,n=function(c,b,e,d){e=pa.call(Polymer.Base,c,b,e,d);var f="property";d&&d.propertyName?b=d.propertyName:f=d&&d.kind||"property";return a(c,b,f,e)};Polymer.Base.w=n;if(Polymer.Base.w!==n)throw Error("Cannot replace _computeFinalAnnotationValue.  Is Polymer frozen?");}else{var T=Polymer.f,n=function(c,b,e,d){c=T?T.call(Polymer,c,b,e,d):c;return a(d,b,e,c)};Polymer.f=n;if(Polymer.f!==n)throw Error("Cannot install sanitizeDOMValue.  Is Polymer frozen?");
}}var b=[,{filter:null,v:null,j:null,m:null}];b[2]={filter:function(a,b,g){a=g;ca.test(a)&&(-1!=a.indexOf("&")&&(a=a.replace(u,"&amp;")),-1!=a.indexOf("<")&&(a=a.replace(v,"&lt;")),-1!=a.indexOf(">")&&(a=a.replace(w,"&gt;")),-1!=a.indexOf('"')&&(a=a.replace(y,"&quot;")),-1!=a.indexOf("'")&&(a=a.replace(aa,"&#39;")),-1!=a.indexOf("\x00")&&(a=a.replace(ba,"&#0;")));return a},v:null,j:N,m:ja};b[3]={filter:function(a,b,g){a=g;a instanceof K||(a=a.o?a.l():String(a),ia.test(a)||(a="about:invalid#zClosurez"),
a=L(a));return a.l()},v:"about:invalid#zClosurez",j:K,m:ha};b[4]={filter:function(){return"about:invalid#zClosurez"},v:"about:invalid#zClosurez",j:I,m:ga};b[5]={filter:function(){return"zClosurez"},v:"zClosurez",j:G,m:fa};b[7]={filter:function(){return"/*zClosurez*/"},v:"/*zClosurez*/",j:E,m:ea};b[8]={filter:function(a,b,g){g=String(g).toLowerCase();a:{var c=null;(a=Q[a])&&(c=a[b]);if("number"!=typeof c&&((a=Q["*"])&&(c=a[b]),"number"!=typeof c)){b=!1;break a}b=!0===la[c][String(g).toLowerCase()]}return b?
g:"zClosurez"},v:"zClosurez",j:null,m:null};b[9]={filter:function(){return"/*zClosurez*/"},v:"zClosurez",j:A,m:C};b[10]={filter:function(a,b,g){return oa.test(g)?g:"zClosurez"},v:"zClosurez",j:A,m:C};"undefined"!==typeof Polymer&&Polymer.version?a():window.addEventListener("HTMLImportsLoaded",a)})();}());
