(function(){'use strict';var x=this||self,y=function(a,h){a=a.split(".");var c=x;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var l;a.length&&(l=a.shift());)a.length||void 0===h?c[l]&&c[l]!==Object.prototype[l]?c=c[l]:c=c[l]={}:c[l]=h},z=function(a,h,c){return a.call.apply(a.bind,arguments)},B=function(a,h,c){if(!a)throw Error();if(2<arguments.length){var l=Array.prototype.slice.call(arguments,2);return function(){var m=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(m,l);
return a.apply(h,m)}}return function(){return a.apply(h,arguments)}},C=function(a,h,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?C=z:C=B;return C.apply(null,arguments)};var E=function(a){return String(a).replace(/\-([a-z])/g,function(h,c){return c.toUpperCase()})};/*

 Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at
 http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at
 http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at
 http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at
 http://polymer.github.io/PATENTS.txt
*/
var F={align:1,alt:1,"aria-activedescendant":10,"aria-atomic":1,"aria-autocomplete":1,"aria-busy":1,"aria-checked":1,"aria-disabled":1,"aria-dropeffect":1,"aria-expanded":1,"aria-haspopup":1,"aria-hidden":1,"aria-invalid":1,"aria-label":1,"aria-level":1,"aria-live":1,"aria-multiline":1,"aria-multiselectable":1,"aria-orientation":1,"aria-posinset":1,"aria-pressed":1,"aria-readonly":1,"aria-relevant":1,"aria-required":1,"aria-selected":1,"aria-setsize":1,"aria-sort":1,"aria-valuemax":1,"aria-valuemin":1,
"aria-valuenow":1,"aria-valuetext":1,autocapitalize:1,autocomplete:1,autocorrect:1,autofocus:1,bgcolor:1,border:1,checked:1,"class":1,color:1,cols:1,colspan:1,contenteditable:1,dir:8,disabled:1,draggable:1,enctype:1,face:1,"for":10,formenctype:1,frameborder:1,height:1,hidden:1,href:4,hreflang:1,id:10,ismap:1,itemid:1,itemprop:1,itemref:1,itemscope:1,itemtype:1,label:1,lang:1,list:10,loop:1,max:1,maxlength:1,min:1,multiple:1,muted:1,name:10,placeholder:1,preload:1,rel:1,required:1,reversed:1,role:1,
rows:1,rowspan:1,selected:1,shape:1,size:1,sizes:1,span:1,spellcheck:1,src:4,start:1,step:1,style:5,summary:1,tabindex:1,target:8,title:1,translate:1,valign:1,value:1,width:1,wrap:1},G={a:{href:[{c:3}]},area:{href:[{c:3}]},audio:{src:[{c:3}]},blockquote:{cite:[{c:3}]},button:{formaction:[{c:3}],formmethod:[{c:1}],type:[{c:1}]},command:{type:[{c:1}]},content:{select:[{c:1}]},del:{cite:[{c:3}]},details:{open:[{c:1}]},form:{action:[{c:3}],method:[{c:1}]},iframe:{srcdoc:[{c:2}]},img:{src:[{c:3}],srcset:[{c:11}]},
input:{formaction:[{c:3}],formmethod:[{c:1}],pattern:[{c:1}],readonly:[{c:1}],src:[{c:3}],type:[{c:1}]},ins:{cite:[{c:3}]},li:{type:[{c:1}]},link:{href:[{c:3,f:"rel",g:"alternate"},{c:3,f:"rel",g:"author"},{c:3,f:"rel",g:"bookmark"},{c:3,f:"rel",g:"canonical"},{c:3,f:"rel",g:"cite"},{c:3,f:"rel",g:"help"},{c:3,f:"rel",g:"icon"},{c:3,f:"rel",g:"license"},{c:3,f:"rel",g:"next"},{c:3,f:"rel",g:"prefetch"},{c:3,f:"rel",g:"dns-prefetch"},{c:3,f:"rel",g:"prerender"},{c:3,f:"rel",g:"preconnect"},{c:3,f:"rel",
g:"preload"},{c:3,f:"rel",g:"prev"},{c:3,f:"rel",g:"search"},{c:3,f:"rel",g:"subresource"}],media:[{c:1}],nonce:[{c:1}],type:[{c:1}]},menuitem:{icon:[{c:3}]},ol:{type:[{c:1}]},q:{cite:[{c:3}]},script:{nonce:[{c:1}],type:[{c:1}]},source:{media:[{c:1}],src:[{c:3}]},style:{media:[{c:1}],nonce:[{c:1}]},table:{cellpadding:[{c:1}],cellspacing:[{c:1}]},textarea:{readonly:[{c:1}]},time:{datetime:[{c:1}]},video:{autoplay:[{c:1}],controls:[{c:1}],poster:[{c:3}],src:[{c:3}]}},H={a:1,abbr:1,address:1,applet:4,
area:5,article:1,aside:1,audio:1,b:1,base:4,bdi:1,bdo:1,blockquote:1,body:1,br:5,button:1,canvas:1,caption:1,cite:1,code:1,col:5,colgroup:1,command:1,content:1,data:1,datalist:1,dd:1,del:1,details:1,dfn:1,dialog:1,div:1,dl:1,dt:1,em:1,embed:4,fieldset:1,figcaption:1,figure:1,font:1,footer:1,form:1,frame:1,frameset:1,h1:1,h2:1,h3:1,h4:1,h5:1,h6:1,head:1,header:1,hr:5,html:1,i:1,iframe:1,img:5,input:5,ins:1,kbd:1,keygen:5,label:1,legend:1,li:1,link:5,main:1,map:1,mark:1,math:4,menu:1,menuitem:1,meta:4,
meter:1,nav:1,noscript:1,object:4,ol:1,optgroup:1,option:1,output:1,p:1,param:5,picture:1,pre:1,progress:1,q:1,rb:1,rp:1,rt:1,rtc:1,ruby:1,s:1,samp:1,script:3,section:1,select:1,slot:1,small:1,source:5,span:1,strong:1,style:2,sub:1,summary:1,sup:1,svg:4,table:1,tbody:1,td:1,template:4,textarea:6,tfoot:1,th:1,thead:1,time:1,title:6,tr:1,track:5,u:1,ul:1,"var":1,video:1,wbr:5},I=[{auto:!0,ltr:!0,rtl:!0},{_self:!0,_blank:!0}],J={"*":{dir:0,target:1}};var P=function(){if(!K){var a=L,h={};for(c in a)h[c]=a[c];K=h;a=0;for(h=M.length;a<h;++a){var c=M[a];K[c.toLowerCase()]=c}}return K},M="aLink accessKey allowFullscreen bgColor cellPadding cellSpacing codeBase codeType contentEditable crossOrigin dateTime dirName formAction formEnctype formMethod formNoValidate formTarget frameBorder innerHTML innerText inputMode isMap longDesc marginHeight marginWidth maxLength mediaGroup minLength noHref noResize noShade noValidate noWrap nodeValue outerHTML outerText readOnly tabIndex textContent trueSpeed useMap vAlign vLink valueAsDate valueAsNumber valueType".split(" "),
L={accept_charset:"acceptCharset","char":"ch",charoff:"chOff",checked:"defaultChecked","class":"className","for":"htmlFor",http_equiv:"httpEquiv",muted:"defaultMuted",selected:"defaultSelected",value:"defaultValue"},K=null,Q=null;var R={},S=!1,T=0,U=/^(?!(?:annotation-xml|color-profile|font-face|font-face(?:-(?:src|uri|format|name))?|missing-glyph)$)[a-z][a-z.0-9_\u00b7\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u037d\u200c\u200d\u203f-\u2040\u2070-\u218f\u2c00-\u2fef\u3001-\udfff\uf900-\ufdcf\ufdf0-\ufffd]*-[\-a-z.0-9_\u00b7\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u037d\u200c\u200d\u203f-\u2040\u2070-\u218f\u2c00-\u2fef\u3001-\udfff\uf900-\ufdcf\ufdf0-\ufffd]*$/,V=function(a,h){var c=window.customElements;if(S){for(var l=window.Polymer.telemetry.registrations,
m=l.length,r=T;r<m;++r)R[l[r].is]=R;T=m}return c&&c.get(a)||R[a]===R?2:"HTMLUnknownElement"===h.name?1:"HTMLElement"===h.name&&U.test(a)?3:0};var W=/(?!,)([^\t\n\f\r ]+)(?:[\t\n\f\r ]+([.0-9+\-]+[a-z]?))?/gi,X=/[\t\n\f\r ]+/,Y=/[\t\n\f\r ,]+/g,Z=function(a){return(a=a.split(X,2))?{url:a[0],metadata:a[1]}:null},aa=function(a){var h=String(a.url).replace(Y,encodeURIComponent);if(a=a.metadata){Y.lastIndex=0;if(Y.test(a))return null;h+=" "+a}return h},ba=function(a,h,c){return c},da=function(a){function h(e){var g=this.getAttribute(e);return!g||/[\[\{]/.test(e)?null:g}var c=a.reportHandler||void 0,l=a.safeTypesBridge||ba,m=/^$/;if(a=a.allowedIdentifierPrefixes)for(var r=
0,u=a.length;r<u;++r)m=new RegExp(m.source+"|^"+String(a[r]).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"));c&&c(!1,"initResin");var q={},A=[,{h:null,j:function(e,g,b){return b},l:null,m:null},{h:null,j:null,l:null,m:"HTML"},{h:null,j:null,l:"about:invalid#zClosurez",m:"URL"},{h:null,j:null,l:"about:invalid#zClosurez",m:"RESOURCE_URL"},{h:null,j:null,l:"zClosurez",m:"STYLE"},,{h:null,j:null,l:" /*zClosurez*/ ",m:"JAVASCRIPT"},{h:null,j:function(e,g,b){b=String(b).toLowerCase();
a:{var f=null;(e=J[e])&&(f=e[g]);if("number"!==typeof f&&((e=J["*"])&&(f=e[g]),"number"!==typeof f)){g=!1;break a}g=!0===I[f][String(b).toLowerCase()]}return g?b:"zClosurez"},l:"zClosurez",m:null},{h:null,j:null,l:"zClosurez",m:"CONSTANT"},{h:null,j:function(e,g,b){return m.test(b)?b:"zClosurez"},l:"zClosurez",m:"CONSTANT"},{h:function(e,g,b){var f=b;"string"===typeof f&&(f=(f=f.match(W))?f.map(Z).filter(Boolean):[]);if(!Array.isArray(f))return"about:invalid#zClosurez";var k=f;f=[];var d=[],n={};
if(Array.isArray(k))for(var p=0,w=k.length;p<w;++p){var v=k[p],t=v&&v.url;if(t){var D=l(t,"URL",n);if(D){var N=D!==n;(N?f:d).push({url:N?D:t,metadata:v.metadata})}}}else d.push(k);k=d.length?JSON.stringify(d):null;d=q;if(f.length){if(!Array.isArray(f))throw Error();d=f.map(aa).filter(Boolean).join(" , ")||q}k&&c&&c(!0,'Failed to sanitize attribute value of <%s>: <%s %s="%O">: %s',e,e,g,b,k);return d===q?"about:invalid#zClosurez":d},j:null,l:null,m:null}],O={},ca=document.createElement("polyresinuncustomized");
return function(e,g,b,f){if(!f&&f!==document.all)return f;var k=e.nodeType;if(k!==Node.ELEMENT_NODE){if(k===Node.TEXT_NODE){k=e.parentElement;g=!k;if(k&&k.nodeType===Node.ELEMENT_NODE){var d=k.localName;switch(V(d,k.constructor)){case 0:case 1:k=Object.hasOwnProperty.call(H,d)?H[d]:null;g=1===k||6===k;break;case 3:case 2:g=!0}}if(g)return""+l(f,"STRING",f)}c&&c(!0,"Failed to sanitize %s %s%s node to value %O",e.parentElement&&e.parentElement.nodeName,"#text","",f);return"zClosurez"}k=e.localName;
var n=e.localName;if(e.getAttribute("is")||2!==V(n,e.constructor)){var p=O[n];p||(p=O[n]=document.createElement(n));n=p}else n=ca;switch(b){case "attribute":p=String(g).toLowerCase();var w=P()[p];if(("string"==typeof w?w:E(p))in n)break;return f;case "property":if(g in n)break;p=g.toLowerCase();p=P()[p];if((p="string"==typeof p?p:null)&&p in n)break;return f;default:throw Error(b+": "+typeof b);}if("attribute"==b)g=g.toLowerCase();else{b=Q;if(!b){b=P();n={};for(d in b)n[b[d]]=d;b=Q=n}d=b[g];g="string"==
typeof d?d:String(g).replace(/([A-Z])/g,"-$1").toLowerCase()}a:{e=C(h,e);if(Object.hasOwnProperty.call(G,k)&&(d=G[k],Object.hasOwnProperty.call(d,g)&&(d=d[g],d instanceof Array))){b=null;n=!1;p=0;for(w=d.length;p<w;++p){var v=d[p],t=v.f;if(!t){b=v.c;break a}null===b&&(b={});t=Object.hasOwnProperty.call(b,t)?b[t]:b[t]=e(t);if(t===v.g){b=v.c;break a}null==t&&(n=!0)}if(n){b=null;break a}}e=F[g];b="number"===typeof e?e:null}d=q;e=null;null!=b&&(b=A[b],n=b.m,e=b.l,n&&(d=l(f,n,q)),d===q&&(b.j?(d=""+l(f,
"STRING",f),d=b.j(k,g,d)):b.h&&(d=b.h(k,g,f)),d===e&&(d=q)));d===q&&(d=e||"zClosurez",c&&c(!0,'Failed to sanitize attribute of <%s>: <%s %s="%O">',k,k,g,f));return d}};y("security.polymer_resin.install",function(a){var h=da(a||{});if(/^1\./.test(Polymer.version)){S=!0;var c=Polymer.Base._computeFinalAnnotationValue;a=function(m,r,u,q){u=c.call(this,m,r,u,q);var A="property";q&&q.propertyName?r=q.propertyName:A=q&&q.kind||"property";return h(m,r,A,u)};Polymer.Base._computeFinalAnnotationValue=a;if(Polymer.Base._computeFinalAnnotationValue!==a)throw Error("Cannot replace _computeFinalAnnotationValue.  Is Polymer frozen?");}else{var l=Polymer.sanitizeDOMValue||Polymer.Settings&&
Polymer.Settings.sanitizeDOMValue;a=function(m,r,u,q){m=l?l.call(Polymer,m,r,u,q):m;return q?h(q,r,u,m):"zClosurez"};if(Polymer.Settings&&Polymer.Settings.o)Polymer.Settings.o(a);else if(Polymer.sanitizeDOMValue=a,Polymer.sanitizeDOMValue!==a)throw Error("Cannot install sanitizeDOMValue.  Is Polymer frozen?");}});
y("security.polymer_resin.CONSOLE_LOGGING_REPORT_HANDLER",function(a,h,c){for(var l=[h],m=2,r=arguments.length;m<r;++m)l[m-1]=arguments[m];a?console.warn.apply(console,l):console.log.apply(console,l)});}).call(this);
